<<<<<<< HEAD
const banks = [
  "Abia",
  "Aba 2",
  "Aba 3",
  "Imo Lane",
  "Ohafia",
  "Umuahia",
  "Umunze",
  "Adamawa",
  "Yola",
  "Yola 2",
  "Akwa Ibom",
  "Eket",
  "Ikot Ekpene",
  "Uyo",
  "Uyo 4",
  "Uyo3",
  "Anambra",
  "Awka 2 Branch",
  "Bridge Head",
  "Ekwulobia",
  "Electronics Market",
  "Ihiala",
  "New Market Road",
  "Nkpor",
  "Nnamdi Azikiwe University",
  "Nnewi",
  "Ogidi",
  "Onitsha",
  "Relief Market",
  "Bauchi",
  "Bauchi",
  "Bayelsa",
  "Yenegoa Branch",
  "Benue",
  "Makurdi",
  "Makurdi 2",
  "Otukpo",
  "Borno",
  "Maiduguri 2",
  "Maiduguri 3",
  "Cross River",
  "Chamley (Calabar 3)",
  "Ikom",
  "Mary Slessor",
  "Ogoja",
  "Delta",
  "Agbor",
  "Asaba",
  "Effurun",
  "Ekpan",
  "Ezenei Avenue",
  "ICT",
  "Igbudu Branch",
  "Kwale",
  "Okpanam Road (Asaba 3)",
  "PTI Road",
  "Sapele",
  "Ughelli",
  "Warri",
  "Warri 2",
  "Ebonyi",
  "Abakaliki 2",
  "Afipko",
  "Edo",
  "Benin (Akpakpava)",
  "Benin Agbor Park",
  "Benin Airport Road",
  "Ekenwa Road",
  "Ekpoma",
  "Ikpoba Hill",
  "Ikpoba Slope",
  "Mission Road",
  "Okada",
  "Oregbeni",
  "Sakponba Road",
  "Sapele Road",
  "Univ. of Benin",
  "Uromi",
  "Uselu",
  "Ekiti",
  "Enugu",
  "Enugu 2",
  "Estate Layout",
  "Ninth Mile",
  "Nsukka",
  "Presidential Road (Enugu 5",
  "Zik Avenue",
  "FCT, Abuja",
  "Adetokunbo Ademola (Abuja)",
  "Ahmandu Bello Way",
  "Algeria Street (Wuse Annex)",
  "Aminu kano (Wuse 2)",
  "Aminu kano II (Cadastral Zone)",
  "Asokoro",
  "Bwari Main",
  "CBD II (Herbert Macauley Way)",
  "Central Business District",
  "Court of Appeal",
  "Dei-Dei",
  "Durumi",
  "Dutse Alhaji",
  "Eagle",
  "Efab",
  "Enugu House",
  "Federal Secretariat",
  "Future View Plaza (CBD VI)",
  "Gana Street",
  "Garki",
  "Garki Ultra Modern Market",
  "Gwagwalada",
  "Gwarinpa",
  "Herbert Macaulay Way (Wuse IV)",
  "Jabbi",
  "K-city Plaza",
  "Kebbi House",
  "Kubwa",
  "Law School (Bwari)",
  "Maitama 2",
  "Mpape",
  "National Assembly",
  "New Wuse",
  "Oro-Ago Crescent",
  "Silverbird Galleria",
  "Sultan Abubakar Way (AMAC)",
  "Transcorp Hilton",
  "Utako",
  "Wuse",
  "Zuba",
  "Gombe",
  "Imo",
  "Okigwe",
  "Okigwe",
  "Orlu",
  "Owerri",
  "Owerri2",
  "Jigawa",
  "Kazaure",
  "Kaduna",
  "kaduna 3",
  "Kaduna Refinery",
  "Kaduna2",
  "Kafanchan",
  "Zaria",
  "Kano",
  "Gwarzo",
  "Hotoro",
  "Kofar ruwa",
  "Naibawa",
  "Sabon-Gari",
  "Unity Road",
  "Wudil",
  "Zoo",
  "Katsina",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Lokoja",
  "Obajana",
  "Okene",
  "Kwara",
  "Ilorin2",
  "Offa",
  "Lagos",
  "Abule Egba",
  "Acme Road",
  "Adeniran Ogunsanya",
  "Adeola Odeku 2",
  "Adetokunbo Ademola",
  "Adeyemo Alakija",
  "Agege Motor Road",
  "Agidingbi",
  "Aguda",
  "Ahmadu Bello Way (V/I)",
  "Ajah",
  "Akin Adesola",
  "Akowonjo",
  "Alaba 2",
  "Alaka",
  "Alausa",
  "Allen",
  "Allen 2",
  "Aluminium Village",
  "Amuwo Odofin",
  "Anthony Village",
  "Apapa (Warehouse Road)",
  "Apapa Road",
  "Aromire",
  "Awolowo Way",
  "Badagry",
  "Bar Beach",
  "Bolade Oshodi",
  "Bourdillion",
  "Broad Street",
  "Catholic Mission",
  "Charity Oshodi",
  "College of Medcine",
  "College Road",
  "Computer village",
  "Creek Road",
  "Dopemu",
  "Ebute-Ero",
  "Eric-Moore",
  "Falomo",
  "Falomo Roundaout",
  "Festac",
  "Gbagada",
  "Gbagada 2",
  "Gowon Estate",
  "Head Office Annex 3",
  "Herbert Macaulay",
  "Herbert Macaulay 2",
  "Idi-Oro",
  "Idumagbo",
  "Idumota",
  "Iju",
  "Ikeja (Oba Akran)",
  "Ikeja GRA",
  "Ikorodu",
  "Ikorodu 2",
  "Ikorodu Road",
  "Ikota",
  "Ikota Shopping Complex",
  "Ikoyi",
  "Ilupeju",
  "Ilupeju 2",
  "Ipaja (Oke-Odo)",
  "Isaac John",
  "Itire",
  "Ketu",
  "Kingsway",
  "Kofo Abayomi",
  "Ladipo Oluwole",
  "Lagos Central",
  "LASU",
  "Lawanson",
  "Lekki",
  "Lekki Expressway",
  "Lekki Expressway Branch",
  "Ligali Ayorinde",
  "Liverpool",
  "Magodo",
  "Marina",
  "Marina 2",
  "Marine Road",
  "Maryland",
  "Matori",
  "Medical Road",
  "Mobil Road",
  "Mobolaji Bank Anthony",
  "Moloney",
  "Mountain Top (MFM)",
  "Muri Okonola",
  "Oba Akran 2",
  "Ogba",
  "Ogba 2",
  "Ogudu",
  "Ogunlana Drive",
  "Ojodu",
  "Ojokoro",
  "Oke-Arin",
  "Oke-Arin 2",
  "Old Ojo Road",
  "Olosa",
  "Olowu",
  "Opebi",
  "Oregun",
  "Oregun 2",
  "Ozumba Mbadiwe",
  "Ozumba Mbadiwe 2",
  "Palm Avenue",
  "Pen Cinema",
  "Saka Tinubu",
  "Satelite Town",
  "Seme Border",
  "South West Ikoyi",
  "St Finbarrs",
  "Surulere",
  "Tejuosho",
  "Tejuosho Market",
  "Trinity",
  "Trinity 2",
  "Victoria Island",
  "Warehouse Road 2",
  "Wharf Road",
  "Nasarawa",
  "Mararaba",
  "Niger",
  "Kotangora",
  "Minna",
  "Minna II",
  "Suleja",
  "Ogun",
  "Agbara",
  "Akute",
  "Ijebu-Ode",
  "Oke Ilewo",
  "Owode",
  "Redemption Camp",
  "Sagamu",
  "Sango Ota 1",
  "Sango Ota 2",
  "Sango Ota 3",
  "Ondo",
  "Akure 2",
  "Ondo Town",
  "Ore",
  "Osun",
  "Ilesa",
  "Osogbo",
  "Osogbo 2 Branch",
  "Osun",
  "Oyo",
  "Bodija",
  "Ibadan",
  "Ibadan 3",
  "Iwo Road",
  "Mokola",
  "Ojoo Branch",
  "Oluyole Estate",
  "Oyo Town",
  "Saki",
  "Plateau",
  "Jos 2",
  "Rivers",
  "Azikwe PH",
  "Bonny Island",
  "Ikwerre Road",
  "Oginigba",
  "Omoku Ph",
  "Onne",
  "Orije",
  "Oyigbo",
  "Rumuibekwe",
  "Rumukwurushi",
  "Rumuokoro",
  "Rumuola",
  "Trans-Amadi",
  "Woji",
  "Sokoto",
  "Sokoto 3",
  "Sokoto2",
  "Taraba",
  "Wukari",
  "Yobe",
  "Potiskum",
  "Zamfara",
  "Talata Mafara",
];

export default banks;
=======
const banks = [
  "Abia",
  "Aba 2",
  "Aba 3",
  "Imo Lane",
  "Ohafia",
  "Umuahia",
  "Umunze",
  "Adamawa",
  "Yola",
  "Yola 2",
  "Akwa Ibom",
  "Eket",
  "Ikot Ekpene",
  "Uyo",
  "Uyo 4",
  "Uyo3",
  "Anambra",
  "Awka 2 Branch",
  "Bridge Head",
  "Ekwulobia",
  "Electronics Market",
  "Ihiala",
  "New Market Road",
  "Nkpor",
  "Nnamdi Azikiwe University",
  "Nnewi",
  "Ogidi",
  "Onitsha",
  "Relief Market",
  "Bauchi",
  "Bauchi",
  "Bayelsa",
  "Yenegoa Branch",
  "Benue",
  "Makurdi",
  "Makurdi 2",
  "Otukpo",
  "Borno",
  "Maiduguri 2",
  "Maiduguri 3",
  "Cross River",
  "Chamley (Calabar 3)",
  "Ikom",
  "Mary Slessor",
  "Ogoja",
  "Delta",
  "Agbor",
  "Asaba",
  "Effurun",
  "Ekpan",
  "Ezenei Avenue",
  "ICT",
  "Igbudu Branch",
  "Kwale",
  "Okpanam Road (Asaba 3)",
  "PTI Road",
  "Sapele",
  "Ughelli",
  "Warri",
  "Warri 2",
  "Ebonyi",
  "Abakaliki 2",
  "Afipko",
  "Edo",
  "Benin (Akpakpava)",
  "Benin Agbor Park",
  "Benin Airport Road",
  "Ekenwa Road",
  "Ekpoma",
  "Ikpoba Hill",
  "Ikpoba Slope",
  "Mission Road",
  "Okada",
  "Oregbeni",
  "Sakponba Road",
  "Sapele Road",
  "Univ. of Benin",
  "Uromi",
  "Uselu",
  "Ekiti",
  "Enugu",
  "Enugu 2",
  "Estate Layout",
  "Ninth Mile",
  "Nsukka",
  "Presidential Road (Enugu 5",
  "Zik Avenue",
  "FCT, Abuja",
  "Adetokunbo Ademola (Abuja)",
  "Ahmandu Bello Way",
  "Algeria Street (Wuse Annex)",
  "Aminu kano (Wuse 2)",
  "Aminu kano II (Cadastral Zone)",
  "Asokoro",
  "Bwari Main",
  "CBD II (Herbert Macauley Way)",
  "Central Business District",
  "Court of Appeal",
  "Dei-Dei",
  "Durumi",
  "Dutse Alhaji",
  "Eagle",
  "Efab",
  "Enugu House",
  "Federal Secretariat",
  "Future View Plaza (CBD VI)",
  "Gana Street",
  "Garki",
  "Garki Ultra Modern Market",
  "Gwagwalada",
  "Gwarinpa",
  "Herbert Macaulay Way (Wuse IV)",
  "Jabbi",
  "K-city Plaza",
  "Kebbi House",
  "Kubwa",
  "Law School (Bwari)",
  "Maitama 2",
  "Mpape",
  "National Assembly",
  "New Wuse",
  "Oro-Ago Crescent",
  "Silverbird Galleria",
  "Sultan Abubakar Way (AMAC)",
  "Transcorp Hilton",
  "Utako",
  "Wuse",
  "Zuba",
  "Gombe",
  "Imo",
  "Okigwe",
  "Okigwe",
  "Orlu",
  "Owerri",
  "Owerri2",
  "Jigawa",
  "Kazaure",
  "Kaduna",
  "kaduna 3",
  "Kaduna Refinery",
  "Kaduna2",
  "Kafanchan",
  "Zaria",
  "Kano",
  "Gwarzo",
  "Hotoro",
  "Kofar ruwa",
  "Naibawa",
  "Sabon-Gari",
  "Unity Road",
  "Wudil",
  "Zoo",
  "Katsina",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Lokoja",
  "Obajana",
  "Okene",
  "Kwara",
  "Ilorin2",
  "Offa",
  "Lagos",
  "Abule Egba",
  "Acme Road",
  "Adeniran Ogunsanya",
  "Adeola Odeku 2",
  "Adetokunbo Ademola",
  "Adeyemo Alakija",
  "Agege Motor Road",
  "Agidingbi",
  "Aguda",
  "Ahmadu Bello Way (V/I)",
  "Ajah",
  "Akin Adesola",
  "Akowonjo",
  "Alaba 2",
  "Alaka",
  "Alausa",
  "Allen",
  "Allen 2",
  "Aluminium Village",
  "Amuwo Odofin",
  "Anthony Village",
  "Apapa (Warehouse Road)",
  "Apapa Road",
  "Aromire",
  "Awolowo Way",
  "Badagry",
  "Bar Beach",
  "Bolade Oshodi",
  "Bourdillion",
  "Broad Street",
  "Catholic Mission",
  "Charity Oshodi",
  "College of Medcine",
  "College Road",
  "Computer village",
  "Creek Road",
  "Dopemu",
  "Ebute-Ero",
  "Eric-Moore",
  "Falomo",
  "Falomo Roundaout",
  "Festac",
  "Gbagada",
  "Gbagada 2",
  "Gowon Estate",
  "Head Office Annex 3",
  "Herbert Macaulay",
  "Herbert Macaulay 2",
  "Idi-Oro",
  "Idumagbo",
  "Idumota",
  "Iju",
  "Ikeja (Oba Akran)",
  "Ikeja GRA",
  "Ikorodu",
  "Ikorodu 2",
  "Ikorodu Road",
  "Ikota",
  "Ikota Shopping Complex",
  "Ikoyi",
  "Ilupeju",
  "Ilupeju 2",
  "Ipaja (Oke-Odo)",
  "Isaac John",
  "Itire",
  "Ketu",
  "Kingsway",
  "Kofo Abayomi",
  "Ladipo Oluwole",
  "Lagos Central",
  "LASU",
  "Lawanson",
  "Lekki",
  "Lekki Expressway",
  "Lekki Expressway Branch",
  "Ligali Ayorinde",
  "Liverpool",
  "Magodo",
  "Marina",
  "Marina 2",
  "Marine Road",
  "Maryland",
  "Matori",
  "Medical Road",
  "Mobil Road",
  "Mobolaji Bank Anthony",
  "Moloney",
  "Mountain Top (MFM)",
  "Muri Okonola",
  "Oba Akran 2",
  "Ogba",
  "Ogba 2",
  "Ogudu",
  "Ogunlana Drive",
  "Ojodu",
  "Ojokoro",
  "Oke-Arin",
  "Oke-Arin 2",
  "Old Ojo Road",
  "Olosa",
  "Olowu",
  "Opebi",
  "Oregun",
  "Oregun 2",
  "Ozumba Mbadiwe",
  "Ozumba Mbadiwe 2",
  "Palm Avenue",
  "Pen Cinema",
  "Saka Tinubu",
  "Satelite Town",
  "Seme Border",
  "South West Ikoyi",
  "St Finbarrs",
  "Surulere",
  "Tejuosho",
  "Tejuosho Market",
  "Trinity",
  "Trinity 2",
  "Victoria Island",
  "Warehouse Road 2",
  "Wharf Road",
  "Nasarawa",
  "Mararaba",
  "Niger",
  "Kotangora",
  "Minna",
  "Minna II",
  "Suleja",
  "Ogun",
  "Agbara",
  "Akute",
  "Ijebu-Ode",
  "Oke Ilewo",
  "Owode",
  "Redemption Camp",
  "Sagamu",
  "Sango Ota 1",
  "Sango Ota 2",
  "Sango Ota 3",
  "Ondo",
  "Akure 2",
  "Ondo Town",
  "Ore",
  "Osun",
  "Ilesa",
  "Osogbo",
  "Osogbo 2 Branch",
  "Osun",
  "Oyo",
  "Bodija",
  "Ibadan",
  "Ibadan 3",
  "Iwo Road",
  "Mokola",
  "Ojoo Branch",
  "Oluyole Estate",
  "Oyo Town",
  "Saki",
  "Plateau",
  "Jos 2",
  "Rivers",
  "Azikwe PH",
  "Bonny Island",
  "Ikwerre Road",
  "Oginigba",
  "Omoku Ph",
  "Onne",
  "Orije",
  "Oyigbo",
  "Rumuibekwe",
  "Rumukwurushi",
  "Rumuokoro",
  "Rumuola",
  "Trans-Amadi",
  "Woji",
  "Sokoto",
  "Sokoto 3",
  "Sokoto2",
  "Taraba",
  "Wukari",
  "Yobe",
  "Potiskum",
  "Zamfara",
  "Talata Mafara",
];

export default banks;
>>>>>>> d67a1c2f3415f50311b16434b41f1d8f69528f23
